version: "3.9"

services:
  backend:
    image: ${BACKEND_IMAGE}
    pull_policy: always
    restart: unless-stopped

    expose:
      - "8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080

      ConnectionStrings__DefaultConnection: ${ConnectionStrings__DefaultConnection}
      settings__secretKey: ${settings__secretKey}
      Frontend__BaseUrl: ${Frontend__BaseUrl}

      EmailSettings__SmtpHost: ${EmailSettings__SmtpHost}
      EmailSettings__SmtpPort: ${EmailSettings__SmtpPort}
      EmailSettings__SmtpUser: ${EmailSettings__SmtpUser}
      EmailSettings__SmtpPassword: ${EmailSettings__SmtpPassword}
      EmailSettings__FromEmail: ${EmailSettings__FromEmail}
      EmailSettings__FromName: ${EmailSettings__FromName}

      ExternalAirlines__0__name: ${ExternalAirlines__0__name}
      ExternalAirlines__0__airlineId: ${ExternalAirlines__0__airlineId}
      ExternalAirlines__0__url: ${ExternalAirlines__0__url}
      ExternalAirlines__0__token: ${ExternalAirlines__0__token}

    networks:
      - zuli-network

  external-api:
    image: ${EXTERNAL_API_IMAGE}
    pull_policy: always
    restart: unless-stopped

    expose:
      - "7064"

    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:7064
      AllowedHosts: ${ExternalApi__AllowedHosts:-*}

      ConnectionStrings__DefaultConnection: ${ConnectionStrings__DefaultConnection}
      settings__secretKey: ${ExternalApi__SecretKey}
      settings__apiKey: ${ExternalApi__ApiKey}

      AirlineClient__name: ${AirlineClient__name}
      AirlineClient__airlineId: ${AirlineClient__airlineId}
      AirlineClient__url: ${AirlineClient__url}
      AirlineClient__token: ${AirlineClient__token}

    networks:
      - zuli-network

  frontend:
    image: ${FRONTEND_IMAGE}
    pull_policy: always
    restart: unless-stopped

    depends_on:
      - backend

    expose:
      - "80"

    environment:
      NGINX_PROXY_URL: http://backend:8080

    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

    networks:
      - zuli-network

networks:
  zuli-network:
    driver: bridge
