CREATE TABLE Service
(
    Id INT NOT NULL IDENTITY PRIMARY KEY,
    FlightId UNIQUEIDENTIFIER NOT NULL,
    Description VARCHAR(100) NOT NULL,
    CONSTRAINT FK_Service_Flight FOREIGN KEY (FlightId) REFERENCES Flight(Id)
);