CREATE TABLE Flight
(
    FlightId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    aircraftId UNIQUEIDENTIFIER NOT NULL,
    originAirport NVARCHAR(3) NOT NULL,
    destinationAirport NVARCHAR(3) NOT NULL,
    monday BIT NOT NULL,
    tuesday BIT NOT NULL,
    wednesday BIT NOT NULL,
    thursday BIT NOT NULL,
    friday BIT NOT NULL,
    saturday BIT NOT NULL,
    sunday BIT NOT NULL,
    departureTime TIME NOT NULL,
    arrivalTime TIME NOT NULL,
    duration TIME NOT NULL,
    firstClassPrice DECIMAL(18,2) NOT NULL,
    touristPrice DECIMAL(18,2) NOT NULL,
    carryOnPrice DECIMAL(18,2) NOT NULL,
    carryOnWeightKg DECIMAL(10,2) NOT NULL,
    checkedBaggagePrice DECIMAL(18,2) NOT NULL,
    checkedBaggageMaxWeightKg DECIMAL(10,2) NOT NULL,
    checkedBaggageMultiplierPercent DECIMAL(10,2) NOT NULL,
    availableSeats INT NOT NULL,
    status NVARCHAR(50) NULL,
    createdAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
