CREATE TABLE Flight
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Status VARCHAR(20) NOT NULL,
    FlightDate DATETIME NOT NULL,
    TouristPrice DECIMAL(10,2) NOT NULL CHECK (TouristPrice >= 0),
    FirstClassPrice DECIMAL(10,2) NOT NULL CHECK (FirstClassPrice >= 0),
    RealDepartureTime DATETIME NULL,
    RealArrivalTime DATETIME NULL,
    CheckInStartTime DATETIME NULL,
    CheckInDeadline DATETIME NULL,
    AirlineId INT NOT NULL,
    AircraftId UNIQUEIDENTIFIER NOT NULL,
    ItineraryId INT NOT NULL,
    Duration INT NOT NULL,
    CarryOnPrice DECIMAL(8,2),
    CheckedPrice DECIMAL(8,2),
    AvailableSeats INT NOT NULL DEFAULT 0,
    AdminId UNIQUEIDENTIFIER NOT NULL,
    FlightRouteId INT NOT NULL UNIQUE,
    CONSTRAINT FK_Flight_Airline FOREIGN KEY (AirlineId) REFERENCES Airline(AirlineId),
    CONSTRAINT FK_Flight_Aircraft FOREIGN KEY (AircraftId) REFERENCES Aircraft(AircraftId),
    CONSTRAINT FK_Flight_Itinerary FOREIGN KEY (ItineraryId) REFERENCES Itinerary(ItineraryId),
    CONSTRAINT FK_Flight_User FOREIGN KEY (AdminId) REFERENCES [User](UserId),
    CONSTRAINT FK_Flight_Route FOREIGN KEY (FlightRouteId) REFERENCES FlightRoute(FlightRouteId)
);
