name: CI Tests

on:
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: |
          dotnet restore zuli_backend/Tests/Tests.csproj
          dotnet restore zuli_external_API/Tests/Tests.csproj

      - name: Run Backend Tests
        run: dotnet test zuli_backend/Tests/Tests.csproj --no-restore --verbosity normal

      - name: Run External API Tests
        run: dotnet test zuli_external_API/Tests/Tests.csproj --no-restore --verbosity normal